services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env # ADMIN_PASSWORD を共有
    environment:
      VITE_API_BASE: "/api"
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
