services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      # 📦 DB 永続化
      - ./backend/data:/app/data
      # 🖼️ 画像永続化（★追加★）
      - ./backend/uploads:/app/uploads
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE: "/api"
    depends_on:
      - backend
    restart: unless-stopped
